name: Pruebas Automatizadas

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias Python
      run: pip install pytest

    - name: Ejecutar pruebas Python
      run: pytest test/ --maxfail=1 --disable-warnings -q  # ← CORREGIDO: test/ en lugar de tests/

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar Newman
      run: npm install -g newman

    - name: Ejecutar pruebas funcionales con Newman
      run: newman run test/PruebasFuncionales.postman_collection.json